//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBaseApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class R_CC_CUT_OFF_PROCESSING
    {
        public decimal ID { get; set; }
        public string ACTION_TYPE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string TOWN_EXT { get; set; }
        public string FINAL_RUN_IND { get; set; }
        public string CONSUMER_TYPE { get; set; }
        public string STREET_NUMBER { get; set; }
        public string STREET_NAME { get; set; }
        public string SUBURB_DESC { get; set; }
        public string TOWNSHIP_DESC { get; set; }
        public string UNIT_NO { get; set; }
        public string INITIALS { get; set; }
        public string SURNAME { get; set; }
        public string POSTAL_ADDR_LINE1 { get; set; }
        public string POSTAL_ADDR_LINE2 { get; set; }
        public string POSTAL_ADDR_LINE3 { get; set; }
        public Nullable<int> POSTAL_CODE { get; set; }
        public string ID_NO { get; set; }
        public Nullable<int> START_DATE { get; set; }
        public string MAST_ACCT { get; set; }
        public Nullable<decimal> AMT_REQUIRED { get; set; }
        public string AMT_REQUIRED_IND { get; set; }
        public Nullable<decimal> DEPOSIT_AMT { get; set; }
        public string HOME_TEL_NO { get; set; }
        public string WORK_TEL_NO { get; set; }
        public string HOME_AREA_CODE { get; set; }
        public string WORK_AREA_CODE { get; set; }
        public string CELL_TEL_NO { get; set; }
        public string EL_IND { get; set; }
        public string WA_IND { get; set; }
        public string HIGH_IND { get; set; }
        public Nullable<int> BILL_CYCLE { get; set; }
        public string OWNER_IND { get; set; }
        public string SERVICE_IND { get; set; }
        public Nullable<decimal> CURR_BAL { get; set; }
        public string CURR_BAL_IND { get; set; }
        public Nullable<decimal> DAY_30_BAL { get; set; }
        public string DAYS_30_IND { get; set; }
        public Nullable<decimal> DAY_60_BAL { get; set; }
        public string DAYS_60_IND { get; set; }
        public Nullable<decimal> DAY_90_BAL { get; set; }
        public string DAYS_90_IND { get; set; }
        public Nullable<decimal> DAY_120_BAL { get; set; }
        public string DAYS_120_IND { get; set; }
        public string COMPLEX_NO { get; set; }
        public string BUILDING_DESC { get; set; }
        public string BOOK_NO { get; set; }
        public string WA_ROUTE { get; set; }
        public string WA_SERVICE_TYPE { get; set; }
        public Nullable<decimal> WA_SEQUENCE_NO { get; set; }
        public string WA_LAST_READING { get; set; }
        public string WA_READ_DATE { get; set; }
        public string WA_METER_NO { get; set; }
        public string WA_METER_LOCATION { get; set; }
        public string WA_METER_NOTE { get; set; }
        public string EL_ROUTE { get; set; }
        public string EL_SERVICE_TYPE { get; set; }
        public Nullable<decimal> EL_SEQUENCE_NO { get; set; }
        public string EL_LAST_READING { get; set; }
        public string EL_READ_DATE { get; set; }
        public string EL_METER_NO { get; set; }
        public string EL_METER_LOCATION { get; set; }
        public string EL_METER_NOTE { get; set; }
        public string PREPAID_METER1 { get; set; }
        public string PREPAID_METER2 { get; set; }
        public string PREPAID_METER3 { get; set; }
        public Nullable<int> DISCONNECT_DATE { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string FAX_NUMBER { get; set; }
        public Nullable<int> WARD_NUMBER { get; set; }
        public string WARD_DESC { get; set; }
        public string DEBTOR_TYPE { get; set; }
        public string DEBTOR_TYPE_DESC { get; set; }
        public string PROCESS_ID { get; set; }
        public string PROCESSED { get; set; }
        public Nullable<System.DateTime> INSERT_TS { get; set; }

        [NotMapped]
        public String Municipality { get { return GetMunicipality(this.ACCOUNT_NO); } }
        [NotMapped]
        public String CuurentBalance { get { return String.Format("R {0}", this.CURR_BAL); } }
        [NotMapped]
        public String TotalAreas { get { return String.Format("R {0}", this.AMT_REQUIRED); } }


        public string GetMunicipality(string acc)
        {
            string f2 = acc.Replace(" ","").Substring(0, 2);
            string name=string.Empty;
            switch (f2)
            {
                case "18":
                    name = "Edanvale";
                    break;
                case "17":
                    name = "Kempton park";
                    break;
                case "26":
                    name = "Germiston";
                    break;
                case "22":
                    name = "Boskburg";
                    break;
                case "21":
                    name = "Alberton";
                    break;
                case "34":
                    name = "Brakpan";
                    break;
                case "35":
                    name = "Springs";
                    break;
                case "33":
                    name = "Benoni";
                    break;
                case "39":
                    name = "Nigel";
                    break;
            }
            return name;
        }
    }
}
